# Generated by Django 2.2 on 2019-10-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('gennhsh', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.IntegerField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
