# Generated by Django 2.2 on 2019-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
