# Generated by Django 2.2 on 2019-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191024_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fyllo',
            field=models.CharField(choices=[('m', 'Άνδρας'), ('w', 'Γυναίκα')], default='Άνδρας', max_length=7),
        ),
    ]
