# Generated by Django 2.2 on 2019-11-01 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20191024_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaggelma', models.CharField(blank=True, max_length=50, null=True)),
                ('eidikothta', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('polh', models.CharField(blank=True, max_length=50, null=True)),
                ('dieythinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('perioxi', models.CharField(blank=True, max_length=50, null=True)),
                ('tk', models.IntegerField(blank=True, null=True)),
                ('oikogeniaki_katastasi', models.CharField(choices=[('Καμία Επιλογή', 'Καμία Επιλογή'), ('Άγαμος-η', 'Άγαμος-η'), ('Έγγαμος-η', 'Έγγαμος-η'), ('Διαζευγμένος-η', 'Διαζευγμένος-η'), ('Χήρος-α', 'Χήρος-α')], default='Καμία Επιλογή', max_length=15)),
                ('afm', models.IntegerField(blank=True, null=True)),
                ('amka', models.IntegerField(blank=True, null=True)),
                ('doy', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo'),
        ),
    ]
