# Generated by Django 2.2 on 2019-11-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20191101_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='info',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.Customer'),
        ),
    ]
