# Generated by Django 2.2 on 2019-11-01 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20191101_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='afm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='amka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='dieythinsi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='doy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='eidikothta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='epaggelma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='oikogeniaki_katastasi',
            field=models.CharField(choices=[('Καμία Επιλογή', 'Καμία Επιλογή'), ('Άγαμος-η', 'Άγαμος-η'), ('Έγγαμος-η', 'Έγγαμος-η'), ('Διαζευγμένος-η', 'Διαζευγμένος-η'), ('Χήρος-α', 'Χήρος-α')], default='Καμία Επιλογή', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='perioxi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='polh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
