# Generated by Django 2.2 on 2019-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_dj', '0002_auto_20190828_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='megethos',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=2),
        ),
    ]
