# Generated by Django 2.2 on 2019-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_dj', '0004_auto_20190828_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.ManyToManyField(to='nutrition_dj.Category'),
        ),
    ]
