# Generated by Django 2.2 on 2019-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_dj', '0005_auto_20191019_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
