# Generated by Django 2.2 on 2019-10-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_dj', '0008_auto_20191020_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodProduct',
        ),
    ]
