# Generated by Django 2.2 on 2019-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Χωρίς κατηγορία', 'Χωρίς κατηγορία'), ('Γλυκά', 'Γλυκά'), ('Αλμυρά Snack ή Παξιμάδια', 'Αλμυρά Snack ή Παξιμάδια'), ('Αλκοολούχα Ποτά', 'Αλκοολούχα Ποτά'), ('Fast-Food', 'Fast-Food'), ('Γλυκά Snack, Μπισκότα κτλ', 'Γλυκά Snack, Μπισκότα κτλ'), ('Γαλακτομικά', 'Γαλακτομικά'), ('Σάλτσες διάφορες', 'Σάλτσες διάφορες'), ('Ροφήματα', 'Ροφήματα'), ('Έλαια', 'Έλαια'), ('Ζυμαρικά', 'Ζυμαρικά'), ('Φρούτα', 'Φρούτα'), ('Λαχανικά & Σαλάτες', 'Λαχανικά & Σαλάτες'), ('Κόκκινο κρέας', 'Κόκκινο κρέας'), ('Ψάρια', 'Ψάρια'), ('Άλευρα', 'Άλευρα'), ('Αλλαντικά', 'Αλλαντικά'), ('Βότανα & Μυρωδικά', 'Βότανα & Μυρωδικά'), ('Καρποί & Σπόροι', 'Καρποί & Σπόροι'), ('Αναψυκτικά', 'Αναψυκτικά'), ('Ψωμί & Δημητριακά', 'Ψωμί & Δημητριακά'), ('Θαλασσινά', 'Θαλασσινά'), ('Αυγά', 'Αυγά'), ('Παιδικές τροφές', 'Παιδικές τροφές'), ('Λευκό κρέας', 'Λευκό κρέας'), ('Μαγειρεμένα', 'Μαγειρεμένα'), ('Όσπρια', 'Όσπρια'), ('Σούπες', 'Σούπες'), ('Πίτες', 'Πίτες'), ('Επιδόρπιο', 'Επιδόρπιο'), ('Ζωμοί', 'Ζωμοί'), ('Φυτικές τροφές', 'Φυτικές τροφές'), ('Σαλάτες', 'Σαλάτες'), ('Παγωτά', 'Παγωτά'), ('Sandwiches', 'Sandwiches'), ('Σιρόπια', 'Σιρόπια'), ('Χυμοί', 'Χυμοί'), ('Restaurant Foods', 'Restaunt Foods'), ('Βούτυρα', 'Βούτυρα')], default='Χωρίς κατηγορία', max_length=30)),
                ('megethos', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=2)),
                ('energyCal', models.FloatField(default=0)),
                ('energykJ', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carb', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
            ],
        ),
    ]
